# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json tsconfig.json ./

RUN npm install --ignore-scripts

# Copy source code
COPY . .

# Build TypeScript
RUN npm run build

# Ensure dist files are executable
RUN chmod +x dist/*.js

# Default command (overridden by MCP startCommand)
CMD ["node", "dist/index.js"]
